# frozen_string_literal: true

source "https://rubygems.org"

gem 'nokogiri'

gem 'rack', '~>2.2.4'

gem 'rspec'

# Latest version of Jekyll
# gem "jekyll", "~> 3.9.5"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
    gem "tzinfo", "~> 1.2"
    gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
#gem "wdm", ">= 0.1.1", platforms: [:mingw, :x64_mingw, :mswin, :jruby]

# kramdown v2 ships without the gfm parser by default. If you're using
# kramdown v1, comment out this line.
# gem "kramdown-parser-gfm"

gem "webrick", "~> 1.8"

# gem "rails"
